"""initial schema

Revision ID: 2ff8b71ab6a0
Revises: 
Create Date: 2026-06-08 07:27:44.840092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ff8b71ab6a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('certificado',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hash', sa.String(length=64), nullable=False))
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('contenido',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.alter_column('firma',
               existing_type=postgresql.BYTEA(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('accion',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('accion',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.alter_column('firma',
               existing_type=sa.Text(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
        batch_op.alter_column('contenido',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('hash')

    with op.batch_alter_table('certificados', schema=None) as batch_op:
        batch_op.alter_column('certificado',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
